const products = [
  {
    "name": "ULTRABOOST 22 SHOES",
    "slug": "ultraboost-22-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 420,
    "stock": 20,
    "ratings": 4,
    "ratingsCount": 3725,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg",
  },
  {
    "name": "LUNAR NEW YEAR ULTRABOOST DNA SHOES",
    "slug": "lunar-new-year-ultraboost-dna-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 196,
    "stock": 19,
    "ratings": 5,
    "ratingsCount": 4355,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2cee64414e1f4f31baf1ae270099d950_9366/Lunar_New_Year_Ultraboost_DNA_Shoes_Black_GZ6074_01_standard.jpg",
  },
  {
    "name": "SUPERNOVA SHOES",
    "slug": "supernova-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 245,
    "stock": 20,
    "ratings": 4,
    "ratingsCount": 3972,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/69cbc73d0cb846889f89acbb011e68cb_9366/Supernova_Shoes_Black_S42722_01_standard.jpg",
  },
  {
    "name": "LITE RACER ADAPT 3.0 SHOES",
    "slug": "lite-racer-adapt-3.0-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 229,
    "stock": 10,
    "ratings": 5,
    "ratingsCount": 1764,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/96a5f085fedf4e678095abad01056711_9366/Lite_Racer_Adapt_3.0_Shoes_Black_FX8802_01_standard.jpg",
  },
  {
    "name": "4D FWD SHOES",
    "slug": "4d-fwd-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 287,
    "stock": 11,
    "ratings": 4,
    "ratingsCount": 799,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8c5d1994dfd343e28567ad4400dd351d_9366/4DFWD_Shoes_Black_Q46447_01_standard.jpg",
  },
  {
    "name": "KAPTIR 2.0 SHOES",
    "slug": "kaptir-2.0-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 138,
    "stock": 19,
    "ratings": 3,
    "ratingsCount": 4372,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0846e90b15144861b33dacf500e3cfd1_9366/Kaptir_2.0_Shoes_White_H00276_01_standard.jpg",
  },
  {
    "name": "4DFWD PULSE SHOES",
    "slug": "4dfwd-pulse-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 226,
    "stock": 1,
    "ratings": 4,
    "ratingsCount": 2870,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9a8256bb7ca34da49ff8ad5600bb2812_9366/4DFWD_Pulse_Shoes_White_Q46221_01_standard.jpg",
  },
  {
    "name": "ZX 1K BOOST SHOES",
    "slug": "zx-1k-boost-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 319,
    "stock": 7,
    "ratings": 4,
    "ratingsCount": 1360,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0e540bae86d5456aa034ada300ebf46c_9366/ZX_1K_Boost_Shoes_Grey_H00430_01_standard.jpg",
  },
  {
    "name": "NMD_R1 V2 SHOES",
    "slug": "nmd_r1-v2-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 260,
    "stock": 4,
    "ratings": 5,
    "ratingsCount": 1976,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c2a18c4e3f104d52a697ad6a01477bb7_9366/NMD_R1_V2_Shoes_Black_GX6367_01_standard.jpg",
  },
  {
    "name": "NMD_R1 PRIMEBLUE SHOES",
    "slug": "nmd_r1-primeblue-shoes",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 437,
    "stock": 1,
    "ratings": 4,
    "ratingsCount": 565,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0e03e7a2a9cb44dfac2bad6a00f95888_9366/NMD_R1_Primeblue_Shoes_White_GZ9261_01_standard.jpg",
  },
  {
    "name": "TIRO 22 TRACK PANTS",
    "slug": "tiro-22-track-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 109,
    "stock": 6,
    "ratings": 5,
    "ratingsCount": 1688,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9c7058d8677742ac8519ac3f009cdcf4_9366/Tiro_21_Track_Pants_Black_GH7305_21_model.jpg",
  },
  {
    "name": "PRIMEBLUE SST TRACK PANTS",
    "slug": "primeblue-sst-track-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 63,
    "stock": 46,
    "ratings": 4,
    "ratingsCount": 50,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/52b5fde5829a4a04820dacf50127b969_9366/Adicolor_Classics_Primeblue_SST_Track_Pants_Blue_H06714_21_model.jpg",
  },
  {
    "name": "TIRO 21 TRACK PANTS",
    "slug": "tiro-21-track-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 148,
    "stock": 41,
    "ratings": 3,
    "ratingsCount": 4483,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3cb8057730844247a568ac9800fa36fb_9366/Tiro_21_Track_Pants_Blue_GE5425_21_model.jpg",
  },
  {
    "name": "TIRO TRACK PANTS RED",
    "slug": "tiro-track-pants-red",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 122,
    "stock": 43,
    "ratings": 4,
    "ratingsCount": 1239,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c98bbccc77934722b139acb80111a3d7_9366/Tiro_Track_Pants_Red_GT6841_21_model.jpg",
  },
  {
    "name": "TIRO PANTS BLACK GOLD",
    "slug": "tiro-pants-black-gold",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 115,
    "stock": 26,
    "ratings": 5,
    "ratingsCount": 4557,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c447324cf06544b78105ade500fd9e2f_9366/Tiro_Pants_Black_HI1073_21_model.jpg",
  },
  {
    "name": "TAPERED-CUFF 3-STRIPES PANTS",
    "slug": "tapered-cuff-3-stripes-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 108,
    "stock": 5,
    "ratings": 3,
    "ratingsCount": 3383,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c7f050932336444ca286acbb0121f995_9366/Essentials_French_Terry_Tapered-Cuff_3-Stripes_Pants_Grey_GK8824_21_model.jpg",
  },
  {
    "name": "FRENCH TERRY TAPERED CUFF LOGO PANTS",
    "slug": "french-terry-tapered-cuff-logo-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 189,
    "stock": 27,
    "ratings": 3,
    "ratingsCount": 1974,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3fb5325716cc4e45a76bac4700ea31dc_9366/Essentials_French_Terry_Tapered_Cuff_Logo_Pants_Black_GK8968_21_model.jpg",
  },
  {
    "name": "OPEN HEM 3-STRIPES TRACK PANTS",
    "slug": "open-hem-3-stripes-track-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 58,
    "stock": 41,
    "ratings": 5,
    "ratingsCount": 2140,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d47f8bc94b2c401b9eafad23007fd8c4_9366/Primegreen_Essentials_Warm-Up_Open_Hem_3-Stripes_Track_Pants_Black_H48430_21_model.jpg",
  },
  {
    "name": "ESSENTIALS4GAMEDAY PANTS",
    "slug": "essentials4gameday-pants",
    "category": "Men's Pants",
    "brand": "Addidas",
    "price": 185,
    "stock": 43,
    "ratings": 5,
    "ratingsCount": 2676,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/64f1ba254925439d88eaad920127d77e_9366/Essentials4Gameday_Pants_Black_HE1800_21_model.jpg",
  },
  {
    "name": "TERREX AX4 MID GORE-TEX HIKING SHOES",
    "slug": "terrex-ax4-mid-gore-tex-hiking-shoes",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 111,
    "stock": 19,
    "ratings": 4,
    "ratingsCount": 894,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/dfa8c9a7d2864065b27fad7400b2e05e_9366/Terrex_AX4_Mid_GORE-TEX_Hiking_shoes_Black_FY9638_01_standard.jpg",
  },
  {
    "name": "RESPONSE 3MC ADV BOOTS",
    "slug": "response-3mc-adv-boots",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 104,
    "stock": 6,
    "ratings": 5,
    "ratingsCount": 354,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b513f2cec8b440978d60ab6d014ad452_9366/Response_3MC_ADV_Boots_Black_EG9391_01_standard.jpg",
  },
  {
    "name": "Superstar Boots",
    "slug": "superstar-boots",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 151,
    "stock": 13,
    "ratings": 3,
    "ratingsCount": 1010,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6853ac5565a9407bae19ac080120d9d7_9366/Superstar_Boots_Red_FZ2642_01_standard.jpg",
  },
  {
    "name": "TACTICAL LEXICON ADV BOOTS",
    "slug": "tactical-lexicon-adv-boots",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 199,
    "stock": 14,
    "ratings": 4,
    "ratingsCount": 2422,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3a819de9f29c498fae13ab6d01473c4d_9366/Tactical_Lexicon_ADV_Boots_White_EG9385_01_standard.jpg",
  },
  {
    "name": "TERREX TRAILMAKER MID COLD.RDY HIKING SHOES",
    "slug": "terrex-trailmaker-mid-cold.rdy-hiking-shoes",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 110,
    "stock": 16,
    "ratings": 3,
    "ratingsCount": 1533,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c2ee4c27eba64258bcbaad5100e5d998_9366/Terrex_Trailmaker_Mid_COLD.RDY_Hiking_Shoes_Brown_FZ3370_01_standard.jpg",
  },
  {
    "name": "TERREX FREE HIKER GORE-TEX HIKING SHOES",
    "slug": "terrex-free-hiker-gore-tex-hiking-shoes",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 155,
    "stock": 4,
    "ratings": 5,
    "ratingsCount": 1351,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/efbedb26b92e4affa103ad6b008a789a_9366/Terrex_Free_Hiker_Gore-Tex_Hiking_Shoes_Grey_GZ0356_01_standard.jpg",
  },
  {
    "name": "TERREX AGRAVIC TECH PRO TRAIL RUNNING SHOES",
    "slug": "terrex-agravic-tech-pro-trail-running-shoes",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 118,
    "stock": 8,
    "ratings": 3,
    "ratingsCount": 1798,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0a340319370844e99645abc90091df96_9366/Terrex_Agravic_Tech_Pro_Trail_Running_Shoes_Black_FU7634_01_standard.jpg",
  },
  {
    "name": "TERREX FREE HIKER COLD.RDY HIKING BOOTS",
    "slug": "terrex-free-hiker-cold.rdy-hiking-boots",
    "category": "Men's Boot",
    "brand": "Addidas",
    "price": 169,
    "stock": 17,
    "ratings": 5,
    "ratingsCount": 2833,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2ded0bee28b249bbb19cad5000818b77_9366/Terrex_Free_Hiker_COLD.RDY_Hiking_Boots_Black_FZ3364_01_standard.jpg",
  },
  {
    "name": "MOVE FEELREADY SPORT TEE",
    "slug": "move-feelready-sport-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 14,
    "stock": 19,
    "ratings": 3,
    "ratingsCount": 4041,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ec81fbd781fe4aa3a8cead230019c192_9366/AEROREADY_Designed_2_Move_Feelready_Sport_Tee_Burgundy_H30268_21_model.jpg",
  },
  {
    "name": "ADIDAS CAMO BOX GRAPHIC TEE",
    "slug": "adidas-camo-box-graphic-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 16,
    "stock": 10,
    "ratings": 3,
    "ratingsCount": 4505,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/809d5f06a7c74e93aef3ad08017c415a_9366/adidas_Camo_Box_Graphic_Tee_Grey_HB4828_21_model.jpg",
  },
  {
    "name": "ADICOLOR CLASSICS TREFOIL TEE",
    "slug": "adicolor-classics-trefoil-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 20,
    "stock": 12,
    "ratings": 4,
    "ratingsCount": 41,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/de7b5dc9e5a341b9bf5aad570106ba06_9366/Adicolor_Classics_Trefoil_Tee_Burgundy_H06641_21_model.jpg",
  },
  {
    "name": "LNY TREFOIL FILL TEE",
    "slug": "lny-trefoil-fill-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 16,
    "stock": 17,
    "ratings": 4,
    "ratingsCount": 4985,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c53945c38b614702ba6fae1d0164b2f1_9366/LNY_Trefoil_Fill_Tee_Black_HR9040_21_model.jpg",
  },
  {
    "name": "CREATOR 365 TEE",
    "slug": "creator-365-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 34,
    "stock": 20,
    "ratings": 3,
    "ratingsCount": 4727,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/0af79283953e498480c6ac22015ec878_9366/Creator_365_Tee_Black_GL0465_21_model.jpg",
  },
  {
    "name": "OWN THE RUN LONG SLEEVE TEE",
    "slug": "own-the-run-long-sleeve-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 23,
    "stock": 17,
    "ratings": 3,
    "ratingsCount": 4003,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c6a321b7bb7243d28fe9ac71011393c7_9366/Own_the_Run_Long_Sleeve_Tee_Black_GJ9977_21_model.jpg",
  },
  {
    "name": "NYC BADGE OF SPORT LOGO GRAPHIC TEE",
    "slug": "nyc-badge-of-sport-logo-graphic-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 29,
    "stock": 6,
    "ratings": 3,
    "ratingsCount": 805,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e0101e13ac1940208478add1000e953a_9366/NYC_Badge_of_Sport_Logo_Graphic_Tee_White_HE2363_21_model.jpg",
  },
  {
    "name": "RUNNER TEE",
    "slug": "runner-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 20,
    "stock": 7,
    "ratings": 5,
    "ratingsCount": 3343,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8c3f5445517340e8bc02ad8100ffd3f6_9366/Runner_Tee_Burgundy_H25050_21_model.jpg",
  },
  {
    "name": "V-DAY TEE (GENDER NEUTRAL)",
    "slug": "v-day-tee-(gender-neutral)",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 18,
    "stock": 2,
    "ratings": 4,
    "ratingsCount": 1590,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/abfc348baf3243289c4bada000d1238b_9366/V-Day_Tee_(Gender_Neutral)_Pink_HI6014_21_model.jpg",
  },
  {
    "name": "ESSENTIALS COLORBLOCK TEE",
    "slug": "essentials-colorblock-tee",
    "category": "Men's Sneaker",
    "brand": "Addidas",
    "price": 35,
    "stock": 6,
    "ratings": 3,
    "ratingsCount": 2680,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9889d39ac10243a2bb0fad1a0097ef07_9366/Essentials_Colorblock_Tee_Black_H14627_21_model.jpg",
  },
  {
    "name": "3-Stripes Backpack 2.0",
    "slug": "3-stripes-backpack-2.0",
    "category": "Bag",
    "brand": "Addidas",
    "price": 74,
    "stock": 7,
    "ratings": 5,
    "ratingsCount": 365,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/ba79ccb861fd4fd49e3aac9f006a6407_9366/3-Stripes_Backpack_2.0_Grey_EX6735_01_standard.jpg",
  },
  {
    "name": "Trefoil Backpack",
    "slug": "trefoil-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 65,
    "stock": 3,
    "ratings": 4,
    "ratingsCount": 465,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/a520df1b51384c00af9caca100489f04_9366/Trefoil_Backpack_Black_EX6752_01_standard.jpg",
  },
  {
    "name": "Santiago Lunch Bag",
    "slug": "santiago-lunch-bag",
    "category": "Bag",
    "brand": "Addidas",
    "price": 63,
    "stock": 10,
    "ratings": 3,
    "ratingsCount": 346,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/c2aaf5e8a7924f1d9277ac9f005b5f37_9366/Santiago_Lunch_Bag_Black_EX6532_01_standard.jpg",
  },
  {
    "name": "Blue Version Backpack",
    "slug": "blue-version-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 87,
    "stock": 15,
    "ratings": 5,
    "ratingsCount": 234,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/a9e0c5635057425daab5ad0b0089194b_9366/Blue_Version_Backpack_Black_H22735_01_standard.jpg",
  },
  {
    "name": "Defender Backpack",
    "slug": "defender-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 96,
    "stock": 10,
    "ratings": 4,
    "ratingsCount": 241,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/d6ee0177281f42f0a254acb1016aa051_9366/Defender_Backpack_Red_EX7011_01_standard.jpg",
  },
  {
    "name": "Excel Backpack",
    "slug": "excel-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 62,
    "stock": 18,
    "ratings": 5,
    "ratingsCount": 168,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/ac09bb56249b43158485aca1007cc1ef_9366/Excel_Backpack_Black_EX6933_01_standard.jpg",
  },
  {
    "name": "Alliance Sackpack",
    "slug": "alliance-sackpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 99,
    "stock": 16,
    "ratings": 3,
    "ratingsCount": 311,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/2e8a6f09838d49c3b00fad4f0017f753_9366/Alliance_Sackpack_White_FZ6823_01_standard.jpg",
  },
  {
    "name": "R.Y.V. Toploader Backpack",
    "slug": "r.y.v.-toploader-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 56,
    "stock": 19,
    "ratings": 3,
    "ratingsCount": 471,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/1c87c940836e4628852bad130101e5c6_9366/R.Y.V._Toploader_Backpack_Black_H32458_01_standard.jpg",
  },
  {
    "name": "Adicolor Archive Backpack",
    "slug": "adicolor-archive-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 84,
    "stock": 5,
    "ratings": 4,
    "ratingsCount": 445,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/0bb325f9cc174ea4bed7ad9e0101b682_9366/Adicolor_Archive_Backpack_Green_HE9804_01_standard.jpg",
  },
  {
    "name": "R.Y.V. Backpack",
    "slug": "r.y.v.-backpack",
    "category": "Bag",
    "brand": "Addidas",
    "price": 67,
    "stock": 10,
    "ratings": 5,
    "ratingsCount": 83,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/dc7dca21df62473ea518ade101251809_9366/R.Y.V._Backpack_Black_HD9650_01_standard.jpg",
  },
  {
    "name": "Icon Snapback Hat",
    "slug": "icon-snapback-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 21,
    "stock": 13,
    "ratings": 4,
    "ratingsCount": 1,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/1e27ae8bbfb647489261ac8e015d181f_9366/Icon_Snapback_Hat_Grey_EX6798_01_standard.jpg",
  },
  {
    "name": "Superlite Hat",
    "slug": "superlite-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 11,
    "stock": 18,
    "ratings": 3,
    "ratingsCount": 39,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/0ae141db6fce44999337ac8e015954ea_9366/Superlite_Hat_Grey_EX7054_01_standard.jpg",
  },
  {
    "name": "Tee Time 5-Panel Hat",
    "slug": "tee-time-5-panel-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 24,
    "stock": 1,
    "ratings": 4,
    "ratingsCount": 14,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/df67ab60b5574c368b76adf9010f2d2d_9366/Tee_Time_5-Panel_Hat_Black_HA9254_01_standard.jpg",
  },
  {
    "name": "Baseball Cap",
    "slug": "baseball-cap",
    "category": "Cap",
    "brand": "Addidas",
    "price": 17,
    "stock": 7,
    "ratings": 5,
    "ratingsCount": 37,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/0ce5f49aa0914deabf16adc600d09e60_9366/Baseball_Cap_Black_HD7039_01_standard.jpg",
  },
  {
    "name": "Relaxed Strap-Back Hat",
    "slug": "relaxed-strap-back-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 24,
    "stock": 9,
    "ratings": 5,
    "ratingsCount": 15,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/aaa5ae549c624178bc25a740012dd61f_9366/Relaxed_Strap-Back_Hat_White_BH7135_01_standard.jpg",
  },
  {
    "name": "UNISEX ORIGINALS WASHED BUCKET",
    "slug": "unisex-originals-washed-bucket",
    "category": "Cap",
    "brand": "Addidas",
    "price": 27,
    "stock": 14,
    "ratings": 4,
    "ratingsCount": 3,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/e1e758585df14bbbb7d8aaf000c95bd7_9366/UNISEX_ORIGINALS_WASHED_BUCKET_White_CM3933_01_standard.jpg",
  },
  {
    "name": "SST Plus Strap-Back Hat",
    "slug": "sst-plus-strap-back-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 23,
    "stock": 14,
    "ratings": 4,
    "ratingsCount": 32,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/92e77a8d84d845d19171ad50003f2ea1_9366/SST_Plus_Strap-Back_Hat_White_FZ8569_01_standard.jpg",
  },
  {
    "name": "Dispatch Trucker Hat",
    "slug": "dispatch-trucker-hat",
    "category": "Cap",
    "brand": "Addidas",
    "price": 28,
    "stock": 16,
    "ratings": 4,
    "ratingsCount": 30,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/c3981523051c4a978674ad3c01015664_9366/Dispatch_Trucker_Hat_Black_EY5534_01_standard.jpg",
  },
  {
    "name": "adidas Z.N.E. 01 True Wireless Earbuds",
    "slug": "adidas-z.n.e.-01-true-wireless-earbuds",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 142,
    "stock": 11,
    "ratings": 5,
    "ratingsCount": 22,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/00276c6c380b41bcb29fadcc00f98312_9366/adidas_Z.N.E._01_True_Wireless_Earbuds_Grey_EY5116_42_detail.jpg",
  },
  {
    "name": "adidas Z.N.E. 02 ANC True Wireless Earbuds",
    "slug": "adidas-z.n.e.-02-anc-wireless-earbuds",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 135,
    "stock": 16,
    "ratings": 5,
    "ratingsCount": 51,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/b322cdef8e654551ace9adcc00f963ed_9366/adidas_Z.N.E._01_ANC_True_Wireless_Earbuds_Grey_EY5114_41_detail.jpg",
  },
  {
    "name": "FWD-01 Sport In-Ear Headphones",
    "slug": "fwd-01-sport-in-ear-headphones",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 185,
    "stock": 8,
    "ratings": 4,
    "ratingsCount": 66,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/2cdb8652aa2340369ba2aa79010062d1_9366/FWD-01_Sport_In-Ear_Headphones_Black_CM5016_01_standard.jpg",
  },
  {
    "name": "adidas FWD-02 Sport True Wireless Earbuds",
    "slug": "adidas-fwd-02-sport-true-wireless-earbuds",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 162,
    "stock": 14,
    "ratings": 4,
    "ratingsCount": 6,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/523731a02e914d318cb4adcc00f985ba_9366/adidas_FWD-02_Sport_True_Wireless_Earbuds_Grey_EY5113_03_standard_hover.jpg",
  },
  {
    "name": "adidas Z.N.E. 01 ANC True Wireless Earbuds",
    "slug": "adidas-z.n.e.-01-anc-true-wireless-earbuds",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 110,
    "stock": 15,
    "ratings": 5,
    "ratingsCount": 9,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/9e6e7967b3b24ef298f5adcc00f983ec_9366/adidas_Z.N.E._01_ANC_True_Wireless_Earbuds_Grey_EY5115_41_detail.jpg",
  },
  {
    "name": "RPT-01 Sport On-Ear Headphones",
    "slug": "rpt-01-sport-on-ear-headphones",
    "category": "Earphones",
    "brand": "Addidas",
    "price": 170,
    "stock": 15,
    "ratings": 5,
    "ratingsCount": 55,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/c697ceddb0c2469aaa2eaa7101121d10_9366/RPT-01_Sport_On-Ear_Headphones_Black_CM5015_01_standard.jpg",
  },
  {
    "name": "Steel Metal Bottle 1L",
    "slug": "steel-metal-bottle-1l",
    "category": "Bottle",
    "brand": "Addidas",
    "price": 33,
    "stock": 7,
    "ratings": 4,
    "ratingsCount": 62,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/a9c04ca9fa51408faf2fac8e0117abb9_9366/Steel_Metal_Bottle_1L_Black_EX7288_01_standard.jpg",
  },
  {
    "name": "Steel Metal Bottle 600 ML",
    "slug": "steel-metal-bottle-600-ml",
    "category": "Bottle",
    "brand": "Addidas",
    "price": 26,
    "stock": 20,
    "ratings": 5,
    "ratingsCount": 83,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/e2d870a680644e4d98e9ac7d0008ecc7_9366/Steel_Metal_Bottle_600_ML_Yellow_EX7307_01_standard.jpg",
  },
  {
    "name": "Squad Glass Bottle 720 ML",
    "slug": "squad-glass-bottle-720-ml",
    "category": "Bottle",
    "brand": "Addidas",
    "price": 39,
    "stock": 20,
    "ratings": 3,
    "ratingsCount": 1,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/77ad16764abf4e828560ad44001cd640_9366/Squad_Glass_Bottle_720_ML_Black_FZ7115_01_standard.jpg",
  },
  {
    "name": "Steel Bottle 600 ML",
    "slug": "steel-bottle-600-ml",
    "category": "Bottle",
    "brand": "Addidas",
    "price": 23,
    "stock": 11,
    "ratings": 5,
    "ratingsCount": 35,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/48057b65216644f683a9aa1c0172ae6e_9366/Steel_Bottle_600_ML_Black_CL6093_01_standard.jpg",
  },
  {
    "name": "Steel Metal Bottle 2L",
    "slug": "steel-metal-bottle-2l",
    "category": "Bottle",
    "brand": "Addidas",
    "price": 37,
    "stock": 14,
    "ratings": 4,
    "ratingsCount": 68,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis condimentum ligula. Nam at nisl nibh. Donec mollis dui non nisi blandit, non dapibus leo ullamcorper. Fusce blandit vel nibh a commodo. Mauris quis placerat diam. Duis at quam a leo tincidunt molestie in sed turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
    "img": "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/f8d89293c9cb4bf08d52adb100f95a3a_9366/Steel_Metal_Bottle_2L_Black_EX7302_01_standard.jpg",
  }
]

export default products;
